### PR TITLE
add info about on-premises SharePoint

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/960

### CODE REVIEW

**Comment by helenclu** [comment]
@VLG17 , could you include the original issue?

**Comment by VLG17** [comment]
> @VLG17 , could you include the original issue?

Added. Sorry about that.

**Comment by helenclu** [comment]
@VLG17 , the article applies to only SharePoint Online. I don't think we should change the article.

Please check https://social.technet.microsoft.com/Forums/ie/en-US/53e8147d-4d8d-4995-b411-8cc01716a560/promotedlinks-issue-invalid-pageurl?forum=sharepointgeneral, ask the customer which version of SharePoint Server is used, and if the solution in the forum thread works.

**Comment by VLG17** [comment]
> @VLG17 , the article applies to only SharePoint Online. I don't think we should change the article.
> 
> Please check https://social.technet.microsoft.com/Forums/ie/en-US/53e8147d-4d8d-4995-b411-8cc01716a560/promotedlinks-issue-invalid-pageurl?forum=sharepointgeneral, ask the customer which version of SharePoint Server is used, and if the solution in the forum thread works.

@helenclu User confirmed that the issue is afecting SharePoint on-premises also.

**Pull request closed without merging**
