### PR TITLE
update OWA limits

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1300
also, removed one paragraph from "more information" section, as it is not applicable since the last UI update of OWA in Exchange Online

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by helenclu** [comment]
Need confirmation from PG.

**Comment by simonxjx** [comment]
Have taken a test and received the following test result if all result items are selected but left one.

image

**Comment by simonxjx** [comment]
image

**Pull request merged**
