### PR TITLE
Simplified solution

### PR DESCRIPTION
**Pull request by trudolf-msft**

### CODE REVIEW

**Comment by simonxjx** [comment]
@trudolf-msft , the original steps are about installing a language package and checking whether the package is installed correctly. You steps are only talking about how to check whether the package is installed. I understand that the referenced article has the steps about installing a package. However, it would be better that we can provide some steps in our article. By the way, I think there is no **Apply** button after step 3. Can you have a check?

**Comment by trudolf-msft** [comment]
Hi,

The original solution is quite cumbersome (you need to have client OS ISO etc.).
My suggested solution is very easy to implement.

You're right. It's not an "Apply" but "Ok" button.

Mit freundlichen Grüßen / Best regards
Thomas Rudolf
Senior Customer Engineer Messaging | Tel: +49 40 89722 6849 | Mobile: +49 151 5895 6340
***@***.***D77EF1.610B2F20]
Microsoft Deutschland GmbH | Walter-Gropius-Straße 5 | 80807 München
Microsoft Deutschland GmbH | Niederlassung Hamburg | Axel-Springer-Platz 3 | 20355 Hamburg
Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Thorsten Herrmann, Benjamin O. Orndorff, Keith Dolliver | Amtsgericht München, HRB 70438 | http://www.microsoft.com/germany<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2Fgermany&data=04%7C01%7CThomas.Rudolf%40microsoft.com%7Ccd77d8a23d2b438bbea208d8953147de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C637423386189827213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z%2Br%2BSfaq5MFtd63bppO01x6Hw%2B1sXalO%2BWx7VeaiSVs%3D&reserved=0>
Note: This email may contain confidential information. If you are not named on the addressee list, please take no action in relation to this email, do not open any attachment and please contact the sender (details above) immediately.

**Comment by simonxjx** [comment]
@trudolf-msft, I have created a new PR for the change. You can have a check and let me know your comments. https://review.docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/can't-connect-error-searching-people-owa?branch=pr-en-us-2948

**Comment by trudolf-msft** [comment]
Looks great. Thank you!

**Pull request merged**
