### PR TITLE
Update available-resources-errors.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/589
Added info

### CODE REVIEW

**Comment by helenclu** [comment]
@Reeced40 , did you reproduce the issue? We need to verify if the cause is the filter.

**Comment by Reeced40** [comment]
> @Reeced40 , did you reproduce the issue? We need to verify if the cause is the filter.

Hi @helenclu yes it worked for me.

**Comment by helenclu** [comment]
@Reeced40 , please see https://stackoverflow.com/questions/33635128/excel-cannot-complete-task-with-available-resources. Incorrect VBA code may cause the issue. I'd suggest that you collect more information from the customer.

**Comment by helenclu** [comment]
@nam31 , there hasn't been a customer response for 9 days, can we close the issue?

**Comment by nam31** [comment]
> @nam31 , there hasn't been a customer response for 9 days, can we close the issue?

Hi @helenclu , yes we should close this issue.

**Pull request closed without merging**
