### PR TITLE
Update search-results-missing.md

### PR DESCRIPTION
**Pull request by msbemba**
Was able to search minor versions of the document as mentioned by the user. removed mentions of minor versions in this document.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1609

**Comment by PerJarlemark** [comment]
Thank you, but there now is a misleading text on the this page: 
https://support.microsoft.com/en-us/office/draft-items-are-not-crawled-in-sharepoint-9198c307-13d6-425c-a174-542a60e410e4?ui=en-US&rs=en-001&ad=US

The current text states that the default is that minor versions is not indexed, **the default is that they are!** 
when enabling "Draft Item Security" the default is "Any user who can read items"

**Comment by simonxjx** [comment]
Checking.

**Comment by simonxjx** [comment]
[Draft items are not crawled in SharePoint - Office Support (microsoft.com)](https://support.microsoft.com/office/draft-items-are-not-crawled-in-sharepoint-9198c307-13d6-425c-a174-542a60e410e4) is also updated.

**Pull request merged**
