### PR TITLE
Added a subsegment

### PR DESCRIPTION
**Pull request by Batre-MSFT**
Moved couple of links into new subsegments

### CODE REVIEW

**Comment by simonxjx** [comment]
3 items are duplicated, please remove them before we can merge it.

**Comment by simonxjx** [comment]
@Batre-MSFT, plesae delete the duplicated items.

**Comment by Batre-MSFT** [comment]
@simonxjx , what are the duplicates? can you please point out?

**Comment by simonxjx** [comment]
@Batre-MSFT, the following three items are duplicated. 

  - [Control delivery of group email messages to new members](#control-delivery-of-group-email-messages-to-new-members)
  - [Get a copy of group email messages you send](#get-a-copy-of-group-email-messages-you-send)
  - [Email issues in Office 365 Groups](#email-issues-in-office-365-groups)
- Office 365 Groups mail flow
  - [Control delivery of group email messages to new members](#control-delivery-of-group-email-messages-to-new-members)
  - [Get a copy of group email messages you send](#get-a-copy-of-group-email-messages-you-send)
  - [Email issues in Office 365 Groups](#email-issues-in-office-365-groups)

**Comment by Batre-MSFT** [comment]
The request was to move the following three sub-topics into a new topic (named Office 365 Groups mail flow):

Control delivery of group email messages to new members
Get a copy of group email messages you send
Email issues in Office 365 Groups

Please feel free to remove the other occurrences

**Pull request merged**
