### PR TITLE
Registry path was incorrect

### PR DESCRIPTION
**Pull request by joinimran**
The old path was incorrect and I have checked and unable to found the mentioned path. As suggested by user, updated with the correct path.

Problem: https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1347

### CODE REVIEW

**Comment by helenclu** [comment]
@joinimran , the change is incorrect. As mentioned by the user, it's the additional key. So, you shouldn't replace the key, but add the key instead.

**Comment by joinimran** [comment]
Thank @helenclu for pointing this out. This is now corrected.

**Comment by helenclu** [comment]
@joinimran , this change needs further investigation. Please ask more information from the customer about the \<SID>:
1. If the \<SID> is the current user's SID, then the key is the same as one under HKCU. Otherwise, it won't affect the current user's sign-in.
2. If it's `HKEY_USERS\.DEFAULT`, it may affect the current user.

**Comment by helenclu** [comment]
@joinimran , have you heard from the customer? If not, I think the issue can be closed.

**Comment by joinimran** [comment]
Let's close this, Its been 11 days and no feedback from customer.

**Comment by helenclu** [comment]
Close the PR.

**Pull request closed without merging**
