### PR TITLE
add info about supported scenarios

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1181

### CODE REVIEW

**Review by RAJU2529 — COMMENTED** [review]
@VLG17 Which article did you edited?

**Comment by VLG17** [comment]
> @VLG17 Which article did you edited?

[This one](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/cvi-info-does-not-populate-in-meet-now), which was linked by the author

**Comment by RAJU2529** [comment]
@VLG17 . Good work.
But I like to go some suggestion change.
Below line must be added under Not supported section.
*Meet Now** meeting created from within the Teams channels view:

**Review by RAJU2529 — COMMENTED** [review]
Thanks for accepting my suggestion

**Pull request merged**
