### PR TITLE
Update chrome-behavior-affects-applications.md

### PR DESCRIPTION
**Pull request by Ariantor**
Remove the mention of SfB Server 2019 CU3 having the samesite fix.

### CODE REVIEW

**Comment by hpsin** [comment]
#please-merge

**Comment by hpsin** [comment]
@Ariantor  can you update this to indicate when a possible next update will contain the fix? Or note that CU3 did not, and a future one will? Removing it will cause more questions and confusion.

**Comment by hpsin** [comment]
@Ariantor I believe you should be able to close this one on your own as the opener.

**Comment by todmccoy** [comment]
Closing per @hirsin.

**Pull request closed without merging**
