### PR TITLE
update cmdlet

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1638
source: https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by simonxjx** [comment]
@MaratMussabekov , for the second cmdlet, I think that we only need to run the `Set-OwaMailboxPolicy -AllowedMimeTypes @{Add = "text/html"}  -Identity $owapolicy.Identity` cmdlet. Can you have a check?

**Comment by simonxjx** [comment]
@MaratMussabekov , do you have any update?

**Comment by MaratMussabekov** [comment]
Hello @simonxjx ,
I tried to reproduce the issue to test it, however I wasn't able...
By default, "text/html" mime type only presented in ForceSaveMimeTypes parameter, this cmdlet just set it as defauls (adds to ForceSaveMimeTypes and removes from other parameters).
Thank you

**Comment by simonxjx** [comment]
Thanks for the confirmation and the changes make sense.

**Pull request merged**
