### PR TITLE
Change released the Prod

### PR DESCRIPTION
**Pull request by NancyForero**
Updating Documentation after Prod release

### CODE REVIEW

**Comment by simonxjx** [comment]
CI 144119 is created for tracking this PR.

**Comment by NancyForero** [comment]
Hello, what's the ETA for this to be published? Thanks

**Comment by NancyForero** [comment]
IMPORTANT!
Customers are pinging us saying documentation is confusing. When will this PR be merged and doc updated for public? Thanks.

**Comment by NancyForero** [comment]
@simonxjx

**Comment by Cloud-Writer** [comment]
> @simonxjx

Hi @NancyForero, the Docs publishing pipeline is down, so we can't push out this change immediately. While we wait for the publishing to resume, we'll get the updated text edited for language - it needs a few tweaks. Sorry about this. We'll be ready to push this live as soon as the gates open again.

**Comment by NancyForero** [comment]
@simonxjx thanks for the reply. when will this be updated? i still see the old page. thanks.

**Comment by simonxjx** [comment]
The article is updated https://docs.microsoft.com/microsoftteams/troubleshoot/known-issues/cvi-info-does-not-populate-in-meet-now. Thanks.

**Pull request closed without merging**
