### PR TITLE
Update 4k monitor performance article

### PR DESCRIPTION
**Pull request by emilykirby**
Need to add some workarounds and reword the summary/resolution. Please review the wording. Also is there a better way to group the bullet points? Thanks.

### CODE REVIEW

**Comment by simonxjx** [comment]
@emilykirby , The article is updated and you can check. Please also sign the CLA.

**Review by vishnuna1 — APPROVED** [review]

**Comment by vishnuna1** [comment]
@simonxjx Can you tell us when these changes will go live/public?

**Comment by simonxjx** [comment]
@vishnuna1, the change is live.

**Comment by vishnuna1** [comment]
https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-slow-video-meetings-laptops-4k link still points to old information @simonxjx

**Comment by simonxjx** [comment]
@vishnuna1, can you refresh the page and have a double check?

**Comment by vishnuna1** [comment]
@simonxjx . Can you help push these changes please. 

Please change the following **from**

"Status
In upcoming releases, Microsoft will continue to improve the experience of using video, sharing screen, and using a 4K monitor in a meeting"

**To**

"Status
Microsoft is continuing to improve meeting experience by optimizing Audio, Video and Screen sharing when using a 4K monitor. These updates will become available in upcoming client releases.

**Comment by simonxjx** [comment]
@vishnuna1, it is updated.

**Pull request merged**
