### PR TITLE
Create outlook-shows-presence-unknown-for-contacts

### PR DESCRIPTION
**Pull request by premgan**

### CODE REVIEW

**Comment by simonxjx** [comment]
@premgan, plesae let us know why we need to add the content?

**Comment by premgan** [comment]
@simonxjx this is one of the top issues we see in support and hence the request.

**Comment by simonxjx** [comment]
@premgan, CONTENT IDEA REQUEST 126269 is created for this new request, I think we can close this one.

**Comment by simonxjx** [comment]
Close this as CI has been created for this request.

**Pull request closed without merging**
